version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/__pycache__
    networks:
      - app-network
    environment:
      - CORS_ORIGINS=http://localhost:5173,http://frontend:5173
      
  frontend:
    build:
      context: ./weather-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./weather-frontend:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:8000

networks:
  app-network:
    driver: bridge